include:
  - board: xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: totem_right
  - board: xiao_ble
    shield: settings_reset
